import type { Product, Payer, FeeScheduleEntry, Vendor, Order } from './types';

// --- Products (10 items, real HCPCS codes) ---

export const PRODUCTS: Product[] = [
  { id: 'P001', name: 'Compression Stocking BK 18-30mmHg', hcpcsCode: 'A6530', category: 'compression_stocking', vendor: 'Medi USA', msrp: 4500, status: 'active' },
  { id: 'P002', name: 'Compression Stocking BK 30-40mmHg', hcpcsCode: 'A6531', category: 'compression_stocking', vendor: 'Juzo', msrp: 5500, status: 'active' },
  { id: 'P003', name: 'Compression Stocking Thigh 30-40mmHg', hcpcsCode: 'A6534', category: 'compression_stocking', vendor: 'Medi USA', msrp: 7200, status: 'active' },
  { id: 'P004', name: 'Compression Garment NOS', hcpcsCode: 'A6549', category: 'compression_stocking', vendor: 'Solaris', msrp: 9500, status: 'active' },
  { id: 'P005', name: 'Light Compression Bandage Elastic', hcpcsCode: 'A6448', category: 'compression_bandage', vendor: 'BSN Medical', msrp: 550, status: 'active' },
  { id: 'P006', name: 'Light Compression Bandage Non-Elastic', hcpcsCode: 'A6449', category: 'compression_bandage', vendor: 'BSN Medical', msrp: 1200, status: 'active' },
  { id: 'P007', name: 'Pneumatic Compressor Segmental', hcpcsCode: 'E0652', category: 'pneumatic_device', vendor: 'Tactile Medical', msrp: 145000, status: 'active' },
  { id: 'P008', name: 'Segmental Appliance Full Leg', hcpcsCode: 'E0667', category: 'pneumatic_device', vendor: 'Tactile Medical', msrp: 29500, status: 'active' },
  { id: 'P009', name: 'Breast Prosthesis Silicone', hcpcsCode: 'L8030', category: 'breast_prosthesis', vendor: 'Medi USA', msrp: 31000, status: 'active' },
  { id: 'P010', name: 'Mastectomy Bra', hcpcsCode: 'L8000', category: 'mastectomy_bra', vendor: 'Juzo', msrp: 4800, status: 'active' },
];

// --- Payers (5 insurers + Self-Pay) ---

export const PAYERS: Payer[] = [
  { id: 'PAY001', name: 'Medicare', type: 'medicare', coinsurancePercent: 20 },
  { id: 'PAY002', name: 'Anthem Blue Cross', type: 'commercial', coinsurancePercent: 20 },
  { id: 'PAY003', name: 'Aetna', type: 'commercial', coinsurancePercent: 25 },
  { id: 'PAY004', name: 'UnitedHealthcare', type: 'commercial', coinsurancePercent: 20 },
  { id: 'PAY005', name: 'Cigna', type: 'commercial', coinsurancePercent: 30 },
  { id: 'PAY006', name: 'Self-Pay', type: 'self_pay', coinsurancePercent: 100 },
];

// --- Fee Schedule (10 products x 5 payers = 50 entries) ---
// Medicare baseline. Commercial multipliers: Anthem 1.15x, Aetna 1.10x, UHC 1.12x, Cigna 1.08x

const medicareRates: Record<string, number> = {
  A6530: 3800, A6531: 4800, A6534: 6200, A6549: 7800,
  A6448: 450, A6449: 1000, E0652: 120000, E0667: 24500,
  L8030: 28500, L8000: 4200,
};

const multipliers: Record<string, number> = {
  PAY001: 1.00, PAY002: 1.15, PAY003: 1.10, PAY004: 1.12, PAY005: 1.08,
};

function generateFeeSchedule(): FeeScheduleEntry[] {
  const entries: FeeScheduleEntry[] = [];
  const hcpcsCodes = Object.keys(medicareRates);
  const payerIds = Object.keys(multipliers);
  let counter = 1;

  for (const payerId of payerIds) {
    for (const hcpcs of hcpcsCodes) {
      entries.push({
        id: `FS${String(counter).padStart(3, '0')}`,
        payerId,
        hcpcsCode: hcpcs,
        allowedAmount: Math.round(medicareRates[hcpcs] * multipliers[payerId]),
        effectiveDate: '2026-01-01',
      });
      counter++;
    }
  }

  return entries;
}

export const FEE_SCHEDULE: FeeScheduleEntry[] = generateFeeSchedule();

// --- Vendors ---

export const VENDORS: Vendor[] = [
  { id: 'V001', name: 'Medi USA', website: 'mediusa.com' },
  { id: 'V002', name: 'Juzo', website: 'juzo.com' },
  { id: 'V003', name: 'BSN Medical/Essity', website: 'essity.com' },
  { id: 'V004', name: 'Solaris', website: 'sfrmedical.com' },
  { id: 'V005', name: 'Tactile Medical', website: 'tactilemedical.com' },
];

// --- Sample Orders (8 for dashboard + Revenue Intelligence) ---

export const SAMPLE_ORDERS: Order[] = [
  {
    id: 'ORD-2026-0147',
    patientId: 'PT001',
    patient: {
      id: 'PT001',
      firstName: 'Maria',
      lastName: 'Rodriguez',
      dob: '1968-03-15',
      phone: '(555) 234-5678',
      address: '1234 Oak Ave, Sacramento, CA 95814',
      diagnosisCode: 'I97.2',
      diagnosisDescription: 'Postmastectomy lymphedema syndrome',
    },
    referringProvider: { name: 'Dr. Sarah Chen', npi: '1234567890', clinic: 'Pacific Lymphedema Clinic' },
    payerId: 'PAY002',
    payerName: 'Anthem Blue Cross',
    status: 'submitted',
    lineItems: [
      {
        id: 'LI001',
        productId: 'P002',
        hcpcsCode: 'A6531',
        productName: 'Compression Stocking BK 30-40mmHg',
        vendor: 'Juzo',
        quantity: 2,
        modifier: 'KX',
        allowedAmount: 5520,
        totalAmount: 11040,
        pricingConfidence: 'exact',
      },
      {
        id: 'LI002',
        productId: 'P008',
        hcpcsCode: 'E0667',
        productName: 'Segmental Appliance Full Leg',
        vendor: 'Tactile Medical',
        quantity: 1,
        modifier: 'NU',
        allowedAmount: 28175,
        totalAmount: 28175,
        pricingConfidence: 'exact',
      },
    ],
    totalAllowedAmount: 39215,
    insurancePays: 31372,
    patientResponsibility: 7843,
    createdAt: '2026-03-05T10:30:00Z',
    updatedAt: '2026-03-05T14:15:00Z',
    notes: 'Patient prefers delivery to clinic for fitting appointment.',
  },
  {
    id: 'ORD-2026-0148',
    patientId: 'PT002',
    patient: {
      id: 'PT002',
      firstName: 'James',
      lastName: 'Wilson',
      dob: '1955-11-22',
      phone: '(555) 876-5432',
      address: '567 Pine St, Fresno, CA 93710',
      diagnosisCode: 'I89.0',
      diagnosisDescription: 'Lymphedema, not elsewhere classified',
    },
    referringProvider: { name: 'Dr. Michael Park', npi: '9876543210', clinic: 'Valley Physical Therapy' },
    payerId: 'PAY001',
    payerName: 'Medicare',
    status: 'approved',
    lineItems: [
      {
        id: 'LI003',
        productId: 'P007',
        hcpcsCode: 'E0652',
        productName: 'Pneumatic Compressor Segmental',
        vendor: 'Tactile Medical',
        quantity: 1,
        modifier: 'NU',
        allowedAmount: 120000,
        totalAmount: 120000,
        pricingConfidence: 'exact',
      },
      {
        id: 'LI004a',
        productId: 'P001',
        hcpcsCode: 'A6530',
        productName: 'Compression Stocking BK 18-30mmHg',
        vendor: 'Medi USA',
        quantity: 1,
        modifier: 'RT',
        allowedAmount: 3800,
        totalAmount: 3800,
        pricingConfidence: 'exact',
      },
      {
        id: 'LI004b',
        productId: 'P001',
        hcpcsCode: 'A6530',
        productName: 'Compression Stocking BK 18-30mmHg',
        vendor: 'Medi USA',
        quantity: 1,
        modifier: 'LT',
        allowedAmount: 3800,
        totalAmount: 3800,
        pricingConfidence: 'exact',
      },
    ],
    totalAllowedAmount: 127600,
    insurancePays: 102080,
    patientResponsibility: 25520,
    createdAt: '2026-03-06T09:00:00Z',
    updatedAt: '2026-03-07T11:30:00Z',
    notes: '',
  },
  {
    id: 'ORD-2026-0149',
    patientId: 'PT003',
    patient: {
      id: 'PT003',
      firstName: 'Susan',
      lastName: 'Thompson',
      dob: '1972-07-08',
      phone: '(555) 345-6789',
      address: '890 Elm Dr, San Jose, CA 95112',
      diagnosisCode: 'C50.9',
      diagnosisDescription: 'Malignant neoplasm of breast, unspecified',
    },
    referringProvider: { name: 'Dr. Lisa Adams', npi: '5551234567', clinic: "Women's Health Center" },
    payerId: 'PAY006',
    payerName: 'Self-Pay',
    status: 'draft',
    lineItems: [
      {
        id: 'LI005',
        productId: 'P009',
        hcpcsCode: 'L8030',
        productName: 'Breast Prosthesis Silicone',
        vendor: 'Medi USA',
        quantity: 1,
        modifier: null,
        allowedAmount: 31000,
        totalAmount: 31000,
        pricingConfidence: 'fallback',
      },
      {
        id: 'LI006',
        productId: 'P010',
        hcpcsCode: 'L8000',
        productName: 'Mastectomy Bra',
        vendor: 'Juzo',
        quantity: 1,
        modifier: null,
        allowedAmount: 4800,
        totalAmount: 4800,
        pricingConfidence: 'fallback',
      },
    ],
    totalAllowedAmount: 35800,
    insurancePays: 0,
    patientResponsibility: 35800,
    createdAt: '2026-03-08T16:45:00Z',
    updatedAt: '2026-03-08T16:45:00Z',
    notes: 'Patient requested sizing consultation before order.',
  },
  {
    id: 'ORD-2026-0144',
    patientId: 'PT004',
    patient: {
      id: 'PT004',
      firstName: 'Robert',
      lastName: 'Chang',
      dob: '1961-09-03',
      phone: '(555) 456-7890',
      address: '2345 Maple Ct, Oakland, CA 94610',
      diagnosisCode: 'I89.0',
      diagnosisDescription: 'Lymphedema, not elsewhere classified',
    },
    referringProvider: { name: 'Dr. Karen Wright', npi: '3216549870', clinic: 'Bay Area Vascular' },
    payerId: 'PAY003',
    payerName: 'Aetna',
    status: 'verified',
    lineItems: [
      {
        id: 'LI007',
        productId: 'P003',
        hcpcsCode: 'A6534',
        productName: 'Compression Stocking Thigh 30-40mmHg',
        vendor: 'Medi USA',
        quantity: 2,
        modifier: 'KX',
        allowedAmount: 6820,
        totalAmount: 13640,
        pricingConfidence: 'exact',
      },
      {
        id: 'LI008',
        productId: 'P004',
        hcpcsCode: 'A6549',
        productName: 'Compression Garment NOS',
        vendor: 'Solaris',
        quantity: 1,
        modifier: 'KX',
        allowedAmount: 8580,
        totalAmount: 8580,
        pricingConfidence: 'exact',
      },
    ],
    totalAllowedAmount: 22220,
    insurancePays: 16665,
    patientResponsibility: 5555,
    createdAt: '2026-03-03T08:15:00Z',
    updatedAt: '2026-03-04T10:00:00Z',
    notes: '',
  },
  {
    id: 'ORD-2026-0145',
    patientId: 'PT005',
    patient: {
      id: 'PT005',
      firstName: 'Linda',
      lastName: 'Martinez',
      dob: '1978-01-20',
      phone: '(555) 567-8901',
      address: '678 Cedar Blvd, San Diego, CA 92101',
      diagnosisCode: 'I97.2',
      diagnosisDescription: 'Postmastectomy lymphedema syndrome',
    },
    referringProvider: { name: 'Dr. James Patel', npi: '6549873210', clinic: 'South Coast Oncology' },
    payerId: 'PAY002',
    payerName: 'Anthem Blue Cross',
    status: 'shipped',
    lineItems: [
      {
        id: 'LI009',
        productId: 'P007',
        hcpcsCode: 'E0652',
        productName: 'Pneumatic Compressor Segmental',
        vendor: 'Tactile Medical',
        quantity: 1,
        modifier: 'NU',
        allowedAmount: 138000,
        totalAmount: 138000,
        pricingConfidence: 'exact',
      },
    ],
    totalAllowedAmount: 138000,
    insurancePays: 110400,
    patientResponsibility: 27600,
    createdAt: '2026-02-28T14:00:00Z',
    updatedAt: '2026-03-06T09:30:00Z',
    notes: 'Shipped via FedEx. Tracking #789456123.',
  },
  {
    id: 'ORD-2026-0146',
    patientId: 'PT006',
    patient: {
      id: 'PT006',
      firstName: 'Patricia',
      lastName: 'Davis',
      dob: '1965-05-12',
      phone: '(555) 678-9012',
      address: '901 Birch Ave, Los Angeles, CA 90012',
      diagnosisCode: 'C50.9',
      diagnosisDescription: 'Malignant neoplasm of breast, unspecified',
    },
    referringProvider: { name: 'Dr. Sarah Chen', npi: '1234567890', clinic: 'Pacific Lymphedema Clinic' },
    payerId: 'PAY004',
    payerName: 'UnitedHealthcare',
    status: 'complete',
    lineItems: [
      {
        id: 'LI010',
        productId: 'P009',
        hcpcsCode: 'L8030',
        productName: 'Breast Prosthesis Silicone',
        vendor: 'Medi USA',
        quantity: 1,
        modifier: null,
        allowedAmount: 31920,
        totalAmount: 31920,
        pricingConfidence: 'exact',
      },
      {
        id: 'LI011',
        productId: 'P010',
        hcpcsCode: 'L8000',
        productName: 'Mastectomy Bra',
        vendor: 'Juzo',
        quantity: 2,
        modifier: null,
        allowedAmount: 4704,
        totalAmount: 9408,
        pricingConfidence: 'exact',
      },
    ],
    totalAllowedAmount: 41328,
    insurancePays: 33062,
    patientResponsibility: 8266,
    createdAt: '2026-02-20T11:00:00Z',
    updatedAt: '2026-03-01T15:45:00Z',
    notes: 'Patient picked up at clinic.',
  },
  {
    id: 'ORD-2026-0143',
    patientId: 'PT007',
    patient: {
      id: 'PT007',
      firstName: 'William',
      lastName: 'Johnson',
      dob: '1950-12-30',
      phone: '(555) 789-0123',
      address: '345 Walnut St, Stockton, CA 95202',
      diagnosisCode: 'I89.0',
      diagnosisDescription: 'Lymphedema, not elsewhere classified',
    },
    referringProvider: { name: 'Dr. Michael Park', npi: '9876543210', clinic: 'Valley Physical Therapy' },
    payerId: 'PAY001',
    payerName: 'Medicare',
    status: 'submitted',
    lineItems: [
      {
        id: 'LI012',
        productId: 'P005',
        hcpcsCode: 'A6448',
        productName: 'Light Compression Bandage Elastic',
        vendor: 'BSN Medical',
        quantity: 4,
        modifier: 'KX',
        allowedAmount: 450,
        totalAmount: 1800,
        pricingConfidence: 'exact',
      },
      {
        id: 'LI013',
        productId: 'P006',
        hcpcsCode: 'A6449',
        productName: 'Light Compression Bandage Non-Elastic',
        vendor: 'BSN Medical',
        quantity: 4,
        modifier: 'KX',
        allowedAmount: 1000,
        totalAmount: 4000,
        pricingConfidence: 'exact',
      },
      {
        id: 'LI014',
        productId: 'P001',
        hcpcsCode: 'A6530',
        productName: 'Compression Stocking BK 18-30mmHg',
        vendor: 'Medi USA',
        quantity: 2,
        modifier: 'LT',
        allowedAmount: 3800,
        totalAmount: 7600,
        pricingConfidence: 'exact',
      },
    ],
    totalAllowedAmount: 13400,
    insurancePays: 10720,
    patientResponsibility: 2680,
    createdAt: '2026-03-07T13:30:00Z',
    updatedAt: '2026-03-07T13:30:00Z',
    notes: 'Multi-layer bandaging kit for CDT.',
  },
  {
    id: 'ORD-2026-0142',
    patientId: 'PT008',
    patient: {
      id: 'PT008',
      firstName: 'Dorothy',
      lastName: 'Kim',
      dob: '1983-04-17',
      phone: '(555) 890-1234',
      address: '456 Cypress Dr, Riverside, CA 92501',
      diagnosisCode: 'I97.2',
      diagnosisDescription: 'Postmastectomy lymphedema syndrome',
    },
    referringProvider: { name: 'Dr. Lisa Adams', npi: '5551234567', clinic: "Women's Health Center" },
    payerId: 'PAY005',
    payerName: 'Cigna',
    status: 'approved',
    lineItems: [
      {
        id: 'LI015',
        productId: 'P002',
        hcpcsCode: 'A6531',
        productName: 'Compression Stocking BK 30-40mmHg',
        vendor: 'Juzo',
        quantity: 2,
        modifier: 'KX',
        allowedAmount: 5184,
        totalAmount: 10368,
        pricingConfidence: 'exact',
      },
    ],
    totalAllowedAmount: 10368,
    insurancePays: 7258,
    patientResponsibility: 3110,
    createdAt: '2026-03-04T16:00:00Z',
    updatedAt: '2026-03-08T09:00:00Z',
    notes: '',
  },
];
